services:
  mysql:
    image: mysql:8.0
    container_name: central-inteligencia-sei-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "troque-por-uma-senha-forte"
      MYSQL_DATABASE: "central_inteligencia_sei"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
